version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.example
    environment:
      DATABASE_URL: $DATABASE_URL      
      PORT: $SERVER_PORT
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
      - /app/node_modules
    networks:
      - apinetwork
        
volumes:
  db:

networks:
  apinetwork:
    driver: bridge
