name: CI


on:
  push:
    branches: [ main ]
    
jobs:

  build:
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/checkout@v2
      
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
        
      - name: install dependencies
        run:  yarn
        
      - name: prisma generate
        run:  yarn generate        
      
      - name: build      
        run:  yarn tsc
        
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "., !node_modules"
          target: "~/app/colleges"
                    
      - name: update api      
        uses: appleboy/scp-action@master      
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}          
          script: |
            cd ~/app/colleges
            yarn             
            yarn generate
            pm2 restart colleges
